# $OpenBSD$

COMMENT =		create and use a local lib/ for perl modules with PERL5LIB

DISTNAME =		local-lib-2.000004

CATEGORIES =		devel


# Perl
PERMIT_PACKAGE_CDROM = Yes

MODULES =		cpan
#MAKE_ENV =		???

.include <bsd.port.mk>