# $OpenBSD$

COMMENT =		create and use a local lib/ for perl modules with PERL5LIB

V =			2.000004
DISTNAME =		local-lib-${V}
PKGNAME =		p5-local-lib-${V}

CATEGORIES =		devel


# Perl
PERMIT_PACKAGE_CDROM = Yes

MODULES =		cpan
CPAN_AUTHOR =		HAARG
#MAKE_ENV =		???

.include <bsd.port.mk>
